### ISSUE TITLE
chat_room・messageコントローラーのリクエストスペックを作成する

### ISSUE THREAD

**Issue by poo3** [poo3/animal-protection#212]

**Comment by poo3** [comment]
rspec実行時に下記エラーが発生

Migrations are pending. To resolve this issue, run:

        rails db:migrate RAILS_ENV=test
No examples found.

**Comment by poo3** [comment]
言われた通り rails db:migarate RAILS_ENV=test を実行すると下記エラーが発生

rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Index name 'index_messages_on_chat_room_id' on table 'messages' already exists
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:1197:in `add_index_options'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/mysql/schema_creation.rb:65:in `index_in_create'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_creation.rb:49:in `block in visit_TableDefinition'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_creation.rb:49:in `map'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_creation.rb:49:in `visit_TableDefinition'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:315:in `create_table'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/mysql/schema_statements.rb:81:in `create_table'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:890:in `block in method_missing'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:858:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:858:in `say_with_time'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:879:in `method_missing'
/app/db/migrate/20210910080935_create_messages.rb:3:in `change'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:828:in `exec_migration'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:811:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:810:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1002:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1363:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1280:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1229:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1229:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1061:in `up'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1036:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/railties/databases.rake:84:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/usr/local/bundle/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.3.7/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.3.7/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'

Caused by:
ArgumentError: Index name 'index_messages_on_chat_room_id' on table 'messages' already exists
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:1197:in `add_index_options'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/mysql/schema_creation.rb:65:in `index_in_create'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_creation.rb:49:in `block in visit_TableDefinition'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_creation.rb:49:in `map'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_creation.rb:49:in `visit_TableDefinition'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:315:in `create_table'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/mysql/schema_statements.rb:81:in `create_table'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:890:in `block in method_missing'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:858:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:858:in `say_with_time'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:879:in `method_missing'
/app/db/migrate/20210910080935_create_messages.rb:3:in `change'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:828:in `exec_migration'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:811:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:810:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1002:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1363:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1280:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1229:in `block in migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1229:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1061:in `up'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:1036:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/railties/databases.rake:84:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/usr/local/bundle/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.3.7/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.3.7/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.3.7/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by poo3** [comment]
既にテーブルが作成されているものに再度作成しようとしているためエラーが発生している可能性があります

**Comment by poo3** [comment]
rails db:migrate:reset RAILS_ENV=testを実行しテスト環境のDBにリセットをかけるとエラーが解決しました
